account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(template_name='account/signup.html'), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', views.logOut, name='logout'),    
]

book/urls.py
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

book_trader/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('books/', include('book.urls')),
    path('admin/', admin.site.urls),
    path('bookshelf/', include('bookshelf.urls')),
    path('account/', include('account.urls')),
    path('trades/', include('trades.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshelf/urls.py
from django.urls import path

from . import views

app_name = 'bookshelf'

urlpatterns = [
    path('', views.index, name='index'),
]

main/urls.py
from django.urls import path

from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('terms/', views.terms, name='terms'),  
]

trades/urls.py
from django.urls import path

from . import views

app_name = 'trades'

urlpatterns = [
    path('account/other/<int:pk>/', views.OtherBookListView.as_view(), name='selectother'),
    path('account/<int:pk>/', views.RequestsListView.as_view(), name='requests'),
    path('<int:pk>/', views.BookListView.as_view(), name='select'),
]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

main/views.py
from django.shortcuts import render 
from django.core.paginator import Paginator
from django.db.models import Q
from book.models import Book, AgeGroupCategory
from account.models import CustomUser


def index(request):
    query = request.GET.get('q')
    zipcode_filter = request.GET.get('z')
    age_group = AgeGroupCategory.objects.all()
    age_group_filter = request.GET.get('age_group')
    category = request.GET.get('category', 'title')
    
    zipcode_search_check = request.GET.get('zipcode_search')
    category_search_check = request.GET.get('category_search')
    
    books = Book.objects.filter(available=True)

    if age_group_filter:
        if age_group_filter!='All':
            books = books.filter(age_group=age_group_filter)

    if query and category_search_check:
        if category == 'title':
            books = books.filter(title__icontains=query)
        elif category == 'author':
            books = books.filter(author__icontains=query)
        elif category == 'language':
            books = books.filter(language__icontains=query)
        elif category == 'genre':
            books = books.filter(genre__icontains=query)
        elif category == 'isbn':
            books = books.filter(isbn__icontains=query)
    
    if zipcode_filter and zipcode_search_check:
        users = CustomUser.objects.filter(zipcode=zipcode_filter)
        books = books.filter(owner_user_id__in=users, available=True)

    sort_by = request.GET.get('sort', '-added_at')
    if sort_by:
        books = books.filter().order_by(sort_by)
    
    paginator = Paginator(books, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'main/index.html', {'page_obj': page_obj, 'age_group': age_group})

def about(request):
    return render( request, 'main/about.html')

def terms(request):
    return render( request, 'main/terms.html')

main/templates/main/about.html
{% extends 'main/base.html'%}

{% block title %} About {% endblock %}

{% block content %}
    <h1>About Our Project</h1>
{% endblock %}

main/templates/main/base.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Book Trader </title>
    </head>

    <body>
        <nav class="px-6 flex justify-between item-center border-b border-gray-300">
            <a href="/" class="mt-1 text-xl font-semibold" style="float: left; width: 60%;"><img src="{% static 'main/images/logo.jpg'%}" width="100%" class="rounded-t-xl" style="padding-left: 1%;"></a>
            <div class="class= px-6 py-6 bg-white rounded-xl gap-3 border border-gray-200" style="float: right; width: 40%;">
                {% if request.user.is_authenticated%}
                    <h3 class="py-3 mt-2 font-semibold text-gray-600">Welcome Back, {{user.username}} !</h3> 
                    <div class="flex justify-between gap-3 text-center">
                        <div class=" px-1 py-3 text-lg font-semibold bg-green-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width: 32%;">
                            <a href="{% url 'bookshelf:index' %}" >My Bookshelf</a></div>
                        <div class="px-1 py-3 text-lg font-semibold bg-lime-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width: 32%;">
                            <a href="{% url 'trades:requests' user.id %}" >Trades / Offers</a></div>
                        <div class="px-1 py-3 text-lg font-semibold bg-red-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width: 32%;">
                            <a href="{% url 'account:logout' %}" >Log Out</a></div>
                    </div>
                {% else %}
                    <h3 class="p-6 font-semibold text-gray-600">Welcome! Ready to trade? Please:</h3> 
                    <div class="flex justify-between gap-3 text-center" style="float: right;">
                        <div class="px-4 py-3 text-lg font-semibold bg-green-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="width:150px">
                            <a href="{% url 'account:signup' %}" >Sign Up</a></div>
                        <div class="px-6 py-3 text-lg font-semibold bg-lime-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-600 hover:text-white" style="width:150px">
                            <a href="{% url 'account:login' %}" >Log In</a></div>
                    </div>
                {% endif %}
            </div>
        </nav>

        <header class="px-6 py-20 masthead border border-gray-200" style="background-image: url('{% static 'main/images/books_header.jpg'%}'); margin-bottom: 3px;"></header>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
        
        <footer class="px-6 py-3 masthead border border-gray-200" style="background-image: url('{% static 'main/images/footer.jpg'%}'); margin-bottom: 3px;">
            <div class="py-6 text-lg text-white text-center">
                <a href="/about" class="px-12">About</a>
                <a href="/terms" class="px-12">Term of use</a>
            </div>
        </footer>
    </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html'%}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
    <div class="flex justify-between">
        <div class="mt-6 px-6 bg-white rounded-xl gap-3" style="float: left; width: 80%;">
            <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
                <h2 class="mb-3 text-2xl text-center">All Books</h2>
                
                <div class="flex gap-6 text-gray-500 px-3">
                    <p><strong>Sort By:</strong> </p>
                    <a href="?sort=-added_at" id="new_sort" data-sort="added_at">Newest ⬇️</a>
                    <a href="?sort=title" id="title_sort" data-sort="title">Title ⬇️</a>
                    <a href="?sort=author" id="author_sort" data-sort="author">Author ⬇️</a>
                </div>
                
                <div class="mt-6 px-6 py-3 bg-white rounded-xl">
                    {% for book in page_obj %}
                        <div class="rounded-xl border border-gray-200 p-2 flex justify-between">
                            <div style="float: left; width:20%">
                                {% if book.image %}
                                    <a href="{% url 'book:detail' book.id %}"><img src="{{ book.image.url }}" width="230" height="300" class="rounded-t-xl"></a>
                                {% else %}
                                    <a href="{% url 'book:detail' book.id %}"><img src="{% static 'main/images/default_image_book.jpg' %}" width="230" height="300" class="rounded-t-xl"></a>
                                {% endif %}
                            </div>

                            <div class="px-8" style="float: left; width:60%">
                                <h2 class="text-gray-800 text-2xl py-2">{{ book.title }}</h2>
                                <h3 class="text-gray-500 px-3"><strong>Author: </strong>{{ book.author }}</h3>
                                <h3 class="text-gray-500 px-3"><strong>Location: </strong>{{ book.owner_user_id.zipcode }}</h3>
                                <h3 class="text-gray-500 px-3"><strong>Language: </strong>{{ book.language }}</h3>
                                <h3 class="text-gray-500 px-3"><strong>Age Group: </strong>{{ book.age_group }}</h3>
                                <h3 class="text-gray-500 px-3"><strong>Genre: </strong>{{ book.genre }}</h3>
                                <div class="text-gray-500 px-3"><h3><strong>Description: </strong>{{ book.description }}</h3></div>
                            </div>

                            <div class="gap-3 mt-3 py-2 text-center text-lg text-grey-400 font-semibold" style="float: right; width: 20%">
                                {% if request.user.is_authenticated%}
                                    {% if request.user == book.owner_user_id %}
                                        <div><a href="{% url 'book:detail' book.id %}" class="mt-3 gap-3 px-4 py-3 text-lg font-semibold bg-green-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width:100%">Details...</a></div>
                                        <div><a href="{% url 'book:edit' book.id %}" class="mt-3 gap-3 px-4 py-3 text-lg font-semibold bg-lime-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width:100%">Edit Book</a></div>
                                        <div><a href="{% url 'book:delete' book.id %}" class="mt-3 gap-3 px-4 py-3 text-lg font-semibold bg-red-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width:100%">Delete!</a></div>
                                    {% else %}
                                        <div><a href="{% url 'trades:select' book.id %}" class="mt-3 gap-3 px-4 py-3 text-lg font-semibold bg-red-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width:100%">Send Offer</a></div>
                                        <div><a href="{% url 'book:detail' book.id %}" class="mt-3 gap-3 px-4 py-3 text-lg font-semibold bg-blue-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width:100%">Details...</a></div>
                                    {% endif %}
                                {% else %}
                                    <div><a href="{% url 'book:detail' book.id %}" class=" px-4 py-3 text-lg font-semibold bg-blue-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-600 hover:text-white" style="float: right; width:100%">Details...</a></div>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="mt-6 px-6 py-6 bg-white rounded-xl">
                    <div class="flex justify-between">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% else %}
                            <span class="opacity-50 cursor-not-allowed">previous</span>
                        {% endif %}

                        <div class="text-gray-500">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</div>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                        {% else %}
                            <span class="opacity-50 cursor-not-allowed">next</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-12 px-6 bg-grey rounded-xl gap-3 border border-gray-200" style="float: left; width: 20%;">
            <form method="GET" >
                <h2 class="mt-4 text-lg text-green-700"> Check all search parameters:</h2>
                <div class = "py-6">
                    <p class="mt-3 block text-gray-700 font-bold mb-2 px-3"><input type="checkbox" name="zipcode_search" id="zipcode_search" value="False">  Enter zipcode to search local</p>
                    <input type="text" name="z" class=" mt-2 rounded-l-lg py-2 px-4 border border-gray-400" style="width: 100%" placeholder="Zip Code">
                </div>
            
                <div class = "py-6">
                    <p class="mt-3 block text-gray-700 font-bold mb-2 px-3"><input type="checkbox" name="category_search" id="category_search" value="False"> Search by: </p>
                    <input type="text" name="q" class=" mt-2 rounded-l-lg py-2 px-4 border border-gray-400" style="width: 100%" placeholder="Search...">

                        <div class="mt-2 px-6">
                            <input type="radio" id="title" name="category" value="title" checked>
                            <label for="title">Title</label>
                        </div>
                        <div class="mt-2 px-6">
                            <input type="radio" id="author" name="category" value="author">
                            <label for="author">Author</label>
                        </div>
                        <div class="mt-2 px-6">
                            <input type="radio" id="language" name="category" value="language">
                            <label for="language">Language</label>
                        </div>
                        <div class="mt-2 px-6">
                            <input type="radio" id="genre" name="category" value="genre">
                            <label for="genre">Genre</label>
                        </div>
                        <div class="mt-2 px-6">
                            <input type="radio" id="isbn" name="category" value="isbn">
                            <label for="isbn">ISBN</label>
                        </div>
                </div>
                <div class="py-6">
                    <div class="mb-4">
                        <label for="age_group" class="block text-gray-700 font-bold mb-2">Choose By Age Group:</label>
                        <select name="age_group" id="age_group" class="mt-2 appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                            <option value="">All</option>
                            {% for ag in age_group %}
                            <option value="{{ ag.id }}" {% if age_group_filter == ag.id %}selected{% endif %}>{{ ag.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                
                <button type="submit" class="mt-2 gap-8 px-8 py-3 text-lg font-semibold bg-green-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-600 hover:text-white" style="float: right; width:80%">Find Books!</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/signup.html
{% extends 'main/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        {% comment %} <div class="mb-3">
            <label class="inline-block mb-2">ZipCode</label><br>
            {{ form.zipcode }}
        </div> {% endcomment %}

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="gap-8 px-8 py-3 text-lg font-semibold bg-green-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-600 hover:text-white ">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/main/terms.html
{% extends 'main/base.html'%}

{% block title %} Terms {% endblock %}

{% block content %}
    <h1>Rule of our trading platform:</h1>
{% endblock %}