book/urls.py
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

book_trader/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('books/', include('book.urls')),
    path('admin/', admin.site.urls),
    path('bookshelf/', include('bookshelf.urls')),
    path('account/', include('account.urls')),
    path('trades/', include('trades.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshelf/urls.py
from django.urls import path

from . import views

app_name = 'bookshelf'

urlpatterns = [
    path('', views.index, name='index'),
]

bookshelf/models.py
from django.db import models

# Create your models here.

bookshelf/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import Q
from book.models import Book, AgeGroupCategory
from account.models import CustomUser

@login_required
def index(request):
    query = request.GET.get('q')
    age_group = AgeGroupCategory.objects.all()
    age_group_filter = request.GET.get('age_group')
    category = request.GET.get('category', 'title')
    
    category_search_check = request.GET.get('category_search')
    
    books = Book.objects.filter(owner_user_id = request.user, available=True)

    if age_group_filter:
        if age_group_filter!='All':
            books = books.filter(age_group=age_group_filter)
            

    if query and category_search_check:
        if category == 'title':
            books = books.filter(title__icontains=query)
        elif category == 'author':
            books = books.filter(author__icontains=query)
        elif category == 'language':
            books = books.filter(language__icontains=query)
        elif category == 'genre':
            books = books.filter(genre__icontains=query)
        elif category == 'isbn':
            books = books.filter(isbn__icontains=query)

    sort_by = request.GET.get('sort', '-added_at')
    if sort_by:
        books = books.order_by(sort_by)

    paginator = Paginator(books, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'bookshelf/index.html', {'page_obj': page_obj, 'age_group': age_group})

bookshelf/templates/bookshelf/index.html
{% extends 'main/base.html'%}
{% load static %}
{% block title %} My Bookshelf {% endblock %}

{% block content %}
    <div class="flex justify-between">
        <div class="mt-6 px-6 bg-white rounded-xl gap-3" style="float: left; width: 80%;">
            <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
                <h2 class="mb-3 text-2xl text-center">My Books</h2>
                
                <div class="flex gap-6 text-gray-500 px-3">
                    <p><strong>Sort By:</strong> </p>
                    <a href="?sort=-added_at" id="new_sort" data-sort="added_at">Newest ⬇️</a>
                    <a href="?sort=title" id="title_sort" data-sort="title">Title ⬇️</a>
                    <a href="?sort=author" id="author_sort" data-sort="author">Author ⬇️</a>
                </div>


                <div class="mt-6 px-6 py-3 bg-white rounded-xl">
                    {% for book in page_obj %}
                        <div class="rounded-xl border border-gray-200 p-2 flex justify-between">
                            <div style="float: left; width:20%">
                                {% if book.image %}
                                    <a href="{% url 'book:detail' book.id %}"><img src="{{ book.image.url }}" width="230" height="300" class="rounded-t-xl"></a>
                                {% else %}
                                    <a href="{% url 'book:detail' book.id %}"><img src="{% static 'main/images/default_image_book.jpg' %}" width="230" height="300" class="rounded-t-xl"></a>
                                {% endif %}
                            </div>

                            <div class="px-8" style="float: left; width:60%">
                                <h2 class="text-gray-800 text-2xl py-2">{{ book.title }}</h2>
                                <h3 class="text-gray-500 px-3"><strong>Author: </strong>{{ book.author }}</h3>
                                <h3 class="text-gray-500 px-3"><strong>Location: </strong>{{ book.owner_user_id.zipcode }}</h3>
                                <h3 class="text-gray-500 px-3"><strong>Language: </strong>{{ book.language }}</h3>
                                <h3 class="text-gray-500 px-3"><strong>Age Group: </strong>{{ book.age_group }}</h3>
                                <h3 class="text-gray-500 px-3"><strong>Genre: </strong>{{ book.genre }}</h3>
                                <div class="text-gray-500 px-3"><h3><strong>Description: </strong>{{ book.description }}</h3></div>
                                
                            </div>

                            <div class="gap-3 mt-3 py-2 text-center text-lg text-grey-400 font-semibold" style="float: right; width: 20%">
                                <div><a href="{% url 'book:detail' book.id %}" class="mt-3 gap-3 px-4 py-3 text-lg font-semibold bg-green-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width:100%">Details...</a></div>
                                <div><a href="{% url 'book:edit' book.id %}" class="mt-3 gap-3 px-4 py-3 text-lg font-semibold bg-lime-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width:100%">Edit Book</a></div>
                                <div><a href="{% url 'book:delete' book.id %}" class="mt-3 gap-3 px-4 py-3 text-lg font-semibold bg-red-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white" style="float: right; width:100%">Delete!</a></div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                
                <div class="mt-6 px-6 py-6 bg-white rounded-xl">
                    <div class="flex justify-between">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% else %}
                            <span class="opacity-50 cursor-not-allowed">previous</span>
                        {% endif %}

                        <div class="text-gray-500">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</div>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                        {% else %}
                            <span class="opacity-50 cursor-not-allowed">next</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-12 px-6 py-3 bg-white rounded-xl gap-3 border border-gray-200" style="float: left; width: 20%;">
            <div class="mt-6 px-4 py-3 text-lg font-semibold text-center bg-blue-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white"><a href="{% url 'book:new' %}">Add Book</a></div>
            <div class="mt-6 px-4 py-3 text-lg font-semibold text-center bg-blue-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-500 hover:text-white"><a href="/">Back To Main</a></div>
                
                <form method="GET" >
                    <div class = "py-6">                    
                        <p class="mt-3 block text-gray-700 font-bold mb-2 px-3"><input type="checkbox" name="category_search" id="category_search" value="False"> Search by: </p>
                        <input type="text" name="q" class=" mt-2 rounded-l-lg py-2 px-4 border border-gray-400" style="width: 100%" placeholder="Search...">

                            <div class="mt-2 px-6">
                                <input type="radio" id="title" name="category" value="title" checked>
                                <label for="title">Title</label>
                            </div>
                            <div class="mt-2 px-6">
                                <input type="radio" id="author" name="category" value="author">
                                <label for="author">Author</label>
                            </div>
                            <div class="mt-2 px-6">
                                <input type="radio" id="language" name="category" value="language">
                                <label for="language">Language</label>
                            </div>
                            <div class="mt-2 px-6">
                                <input type="radio" id="genre" name="category" value="genre">
                                <label for="genre">Genre</label>
                            </div>
                            <div class="mt-2 px-6">
                                <input type="radio" id="isbn" name="category" value="isbn">
                                <label for="isbn">ISBN</label>
                            </div>
                    </div>

                    <div class="py-6">
                        <div class="mb-4">
                            <label for="age_group" class="block text-gray-700 font-bold mb-2">Choose By Age Group:</label>
                            <select name="age_group" id="age_group" class="mt-2 appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                                <option value="">All</option>
                                {% for ag in age_group %}
                                <option value="{{ ag.id }}" {% if age_group_filter == ag.id %}selected{% endif %}>{{ ag.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                <button type="submit" class="mt-2 gap-8 px-8 py-3 text-lg font-semibold bg-green-200 text-grey-400 rounded-xl border-b border-gray-300 hover:bg-gray-600 hover:text-white" style="float: right; width:80%">Find Books!</button>
            </form>
        </div>
    </div>
{% endblock %}